spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d8dkmsek1jcs73945vk0-a.oregon-postgres.render.com:5432/skribbl_clone_db
spring.datasource.username=skribbl_clone_db_user
spring.datasource.password=ZuFspwfoZYFPj0z48O6QRQXsP4vD93va
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.skribbl=DEBUG
logging.level.org.springframework.web.socket=DEBUG

# CORS (adjust for your React dev server)
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Room settings
app.room.code-length=6
app.room.max-idle-minutes=30


